language: ruby
before_script:
- git config --global user.email "ankitjain28may77@gmail.com"
- git config --global user.name "ankitjain28may"
- openssl aes-256-cbc -K $encrypted_cab53b80d065_key -iv $encrypted_cab53b80d065_iv -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- mv ./deploy_key ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ~/.ssh/id_rsa
script:
- chmod +x deploy.sh
- "./deploy.sh"
